export const appName = "Mirea Ninja: Navigator";
export const shortAppName = "Navigator";
export const darkTheme = "night";
export const lightTheme = "corporate";
export const CMSProjectGroupsUrl =
    "https://cms.mirea.ninja/api/landing-project-groups?populate[projectCards][populate]=*";
export const VKLink = "https://vk.com/mirea.ninja";
export const TelegramLink = "https://t.me/mirea_ninja_chat";
export const GitHubLink = "https://github.com/mirea-ninja";
export const navbarIconSizeClassName = "w-7 h-7";
