export const appName = 'Mirea Ninja: Navigator'
export const shortAppName = 'Navigator'
export const appDescription = 'Приложения для студентов МИРЭА'
export const darkTheme = 'night'
export const lightTheme = 'corporate'
export const CMSProjectGroupsUrl =
  'https://cms.mirea.ninja/api/landing-project-groups?populate[projectCards][populate]=*'
export const feedbackURL = 'https://d5d0k8rjhrtud9q2useu.apigw.yandexcloud.net/feedback'
export const VKLink = 'https://vk.com/mirea.ninja'
export const TelegramLink = 'https://t.me/mirea_ninja_chat'
export const GitHubLink = 'https://github.com/mirea-ninja'
export const navbarIconSizeClassName = 'w-7 h-7'
export const maxFeedbackTextLength = 1000
export const maxFeedbackContactLength = 100
